#!/bin/sh

# Started by xinit or startx if it exists. Otherwise /etc/X11/xinit/xinitrc
echo "$BASH_SOURCE" >/tmp/boot_order.log

# merge in defaults and keymaps
_load_xresources() {
  if [ -f "$1" ]; then
    xmodmap "$1"
  fi
}
_load_xrdb_config() {
  if [ -f "$1" ]; then
    xrdb -merge "$1"
  fi
}
_load_xrdb_config /etc/X11/xinit/.Xresources
_load_xresources /etc/X11/xinit/.Xmodmap
_load_xrdb_config $HOME/.Xresources
_load_xresources $HOME/.Xmodmap

# Important: comes from the xinitrc default and arch wiki says not to remove it.
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Note that default settings from /etc/X11/xorg.conf.d/00-keyboard.conf
# are loaded when the X server starts up. Keyboard settings there are
# typically written using localectl.
setxkbmap \
  -model dell101 \
  -layout be,us \
  -variant , \
  -option compose:ins,grp:ctrls_toggle,caps:escape

# Inhibit the screensaver for apps calling to freedesktop.org Indle Inhibition Service
# Note: it forwards to the app xss!
xssproxy &
#xautolock -time 10 -locker "i3lock -c '#000000'" -detectsleep &

exec i3
