#!/bin/sh
echo "$BASH_SOURCE" > /tmp/boot_order.log

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi


# Note that default settings from /etc/X11/xorg.conf.d/00-keyboard.conf
# are loaded when the X server starts up. Keyboard settings there are
# typically written using localectl.
setxkbmap \
    -model pc105 \
    -layout be,us \
    -option compose:sclk,grp:ctrls_toggle,caps:escape
xautolock -time 10 -locker "i3lock -c #000000" -detectsleep &

exec i3 
