[general]
import = [
    "~/.config/alacritty/themes/themes/tender.toml"
    ]

[bell]
animation = "EaseOutSine"
duration = 500

[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#839496"
text = "#002b36"

[colors.hints]
end = { foreground =  "#1d1f21", background = "#e9ff5e" } 
start = { background = "#e9ff5e" ,foreground = "#1d1f21" }

[colors.footer_bar]
background = "0x1d1f21"
foreground = "0xc5c8c6"

[colors.search]
focused_match = { foreground = "CellBackground", background = "0xffffff" }
matches = { background = "#777777", foreground = "#ffffff" }

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 9

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Ultralight"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[hints.enabled]]
binding = { key = "O", mods = "Control|Shift" }
command = "xdg-open"
post_processing = true
regex = "(ipfs|ipns|magnet|mailto|gemini|gopher|https|http|news|file|git|ssh|ftp):[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"
mouse = { enabled = true, mods = "None" }

[[hints.enabled]]
binding = { key = "Y", mods = "Control|Shift" }
action = "Copy"
post_processing = false
regex = '((deployment.app|binding|componentstatuse|configmap|endpoint|event|limitrange|namespace|node|persistentvolumeclaim|persistentvolume|pod|podtemplate|replicationcontroller|resourcequota|secret|serviceaccount|service|mutatingwebhookconfiguration.admissionregistration.k8s.io|validatingwebhookconfiguration.admissionregistration.k8s.io|customresourcedefinition.apiextension.k8s.io|apiservice.apiregistration.k8s.io|controllerrevision.apps|daemonset.apps|deployment.apps|replicaset.apps|statefulset.apps|tokenreview.authentication.k8s.io|localsubjectaccessreview.authorization.k8s.io|selfsubjectaccessreviews.authorization.k8s.io|selfsubjectrulesreview.authorization.k8s.io|subjectaccessreview.authorization.k8s.io|horizontalpodautoscaler.autoscaling|cronjob.batch|job.batch|certificatesigningrequest.certificates.k8s.io|events.events.k8s.io|daemonset.extensions|deployment.extensions|ingress.extensions|networkpolicies.extensions|podsecuritypolicies.extensions|replicaset.extensions|networkpolicie.networking.k8s.io|poddisruptionbudget.policy|clusterrolebinding.rbac.authorization.k8s.io|clusterrole.rbac.authorization.k8s.io|rolebinding.rbac.authorization.k8s.io|role.rbac.authorization.k8s.io|storageclasse.storage.k8s.io)[[:alnum:]_#$%&+=/@-]+)|([0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})|([0-9a-f]{12,128})|([[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3}\.[[:digit:]]{1,3})'

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Control|Shift"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "Copy"
mouse = "Right"

[window.padding]
x = 2
y = 2
